package program;

import database.MySQLConnect;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import util.DateUtilities;
import util.MSG;

public class AddNewMember extends javax.swing.JDialog {

    SimpleDateFormat DatefmtThai = new SimpleDateFormat("dd/MM/yyyy (HH:mm)", Locale.ENGLISH);
    SimpleDateFormat Datefmt = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    SimpleDateFormat ShowDatefmt = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    SimpleDateFormat GetYear = new SimpleDateFormat("yyyy", Locale.ENGLISH);
    SimpleDateFormat GetMonth = new SimpleDateFormat("MM", Locale.ENGLISH);
    SimpleDateFormat GetDate = new SimpleDateFormat("dd", Locale.ENGLISH);
    DecimalFormat DecFmt = new DecimalFormat("##,###,##0.00");
    DecimalFormat IntFmt = new DecimalFormat("##,###,##0");
    DecimalFormat DayFmt = new DecimalFormat("00");
    Date date = new Date();
    Boolean AddNew ;

    /** Creates new form AddNewArCustomer */
    public AddNewMember(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ClearVariable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        M_Code = new javax.swing.JTextField();
        M_Name = new javax.swing.JTextField();
        M_HomeTel = new javax.swing.JTextField();
        M_OfficeTel = new javax.swing.JTextField();
        M_Mobile = new javax.swing.JTextField();
        M_Reamrk1 = new javax.swing.JTextField();
        M_Remark2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        M_Brithday = new javax.swing.JFormattedTextField();
        M_Begin = new javax.swing.JFormattedTextField();
        M_End = new javax.swing.JFormattedTextField();
        cmdDateChoose2 = new javax.swing.JButton();
        cmdDateChoose1 = new javax.swing.JButton();
        cmdDateChoose3 = new javax.swing.JButton();
        ProcessStr = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        M_Barcode = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        M_NewEnd = new javax.swing.JLabel();
        bntCancel = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();
        bntDisplay = new javax.swing.JButton();
        bntExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ปรับรุงรายการข้อมูลสมาชิก");
        setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("รหัสสมาชิก");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ชื่อสมาชิก");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("วันเกิดสมาชิก");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("โทรศัพท์บ้าน");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("โทรศััพท์ที่ทำงาน");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("โทรศัพท์มือถือ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("หมายเหตุ");

        M_Code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        M_Code.setMinimumSize(new java.awt.Dimension(10, 25));
        M_Code.setPreferredSize(new java.awt.Dimension(76, 30));
        M_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_CodeKeyPressed(evt);
            }
        });

        M_Name.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_Name.setMinimumSize(new java.awt.Dimension(10, 25));
        M_Name.setPreferredSize(new java.awt.Dimension(76, 30));
        M_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_NameKeyPressed(evt);
            }
        });

        M_HomeTel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_HomeTel.setPreferredSize(new java.awt.Dimension(10, 30));
        M_HomeTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_HomeTelKeyPressed(evt);
            }
        });

        M_OfficeTel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_OfficeTel.setPreferredSize(new java.awt.Dimension(10, 30));
        M_OfficeTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_OfficeTelKeyPressed(evt);
            }
        });

        M_Mobile.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_Mobile.setPreferredSize(new java.awt.Dimension(10, 30));
        M_Mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_MobileKeyPressed(evt);
            }
        });

        M_Reamrk1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_Reamrk1.setPreferredSize(new java.awt.Dimension(10, 30));
        M_Reamrk1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_Reamrk1KeyPressed(evt);
            }
        });

        M_Remark2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_Remark2.setPreferredSize(new java.awt.Dimension(10, 30));
        M_Remark2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_Remark2KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("วันที่สมัคร");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("วันหมดอายุ");

        M_Brithday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        M_Brithday.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_Brithday.setMinimumSize(new java.awt.Dimension(10, 25));
        M_Brithday.setPreferredSize(new java.awt.Dimension(10, 30));
        M_Brithday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_BrithdayKeyPressed(evt);
            }
        });

        M_Begin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        M_Begin.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_Begin.setPreferredSize(new java.awt.Dimension(10, 30));
        M_Begin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                M_BeginFocusLost(evt);
            }
        });
        M_Begin.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                M_BeginHierarchyChanged(evt);
            }
        });
        M_Begin.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                M_BeginInputMethodTextChanged(evt);
            }
        });
        M_Begin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_BeginKeyPressed(evt);
            }
        });

        M_End.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        M_End.setEnabled(false);
        M_End.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        M_End.setPreferredSize(new java.awt.Dimension(10, 30));
        M_End.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_EndKeyPressed(evt);
            }
        });

        cmdDateChoose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar.png"))); // NOI18N
        cmdDateChoose2.setFocusable(false);
        cmdDateChoose2.setRequestFocusEnabled(false);
        cmdDateChoose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDateChoose2ActionPerformed(evt);
            }
        });

        cmdDateChoose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar.png"))); // NOI18N
        cmdDateChoose1.setFocusable(false);
        cmdDateChoose1.setRequestFocusEnabled(false);
        cmdDateChoose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDateChoose1ActionPerformed(evt);
            }
        });

        cmdDateChoose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar.png"))); // NOI18N
        cmdDateChoose3.setFocusable(false);
        cmdDateChoose3.setRequestFocusEnabled(false);
        cmdDateChoose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDateChoose3ActionPerformed(evt);
            }
        });

        ProcessStr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ProcessStr.setForeground(new java.awt.Color(228, 16, 37));
        ProcessStr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProcessStr.setText("jLabel8");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Barcode");

        M_Barcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                M_BarcodeFocusLost(evt);
            }
        });
        M_Barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                M_BarcodeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(M_Reamrk1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(M_Remark2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M_Begin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M_Brithday, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdDateChoose2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(M_End, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmdDateChoose1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(M_OfficeTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M_HomeTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M_Mobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addComponent(ProcessStr, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(M_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(M_Barcode))
                        .addComponent(M_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDateChoose3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(M_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(M_Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(M_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(M_Brithday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdDateChoose1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdDateChoose3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(M_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(M_Begin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdDateChoose2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(M_HomeTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(M_OfficeTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(M_Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProcessStr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(M_Reamrk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M_Remark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 31, 11)));

        M_NewEnd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        M_NewEnd.setForeground(new java.awt.Color(247, 8, 8));
        M_NewEnd.setText("วันที่หมดอายุบัตรชั่วคราว");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(M_NewEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(M_NewEnd)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        bntCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntCancel.setText("  ยกเลิก  ");
        bntCancel.setFocusable(false);
        bntCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntCancel.setIconTextGap(0);
        bntCancel.setPreferredSize(new java.awt.Dimension(80, 70));
        bntCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bntCancelMouseReleased(evt);
            }
        });
        bntCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelActionPerformed(evt);
            }
        });

        bntSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntSave.setText("บันทึกข้อมูล");
        bntSave.setFocusable(false);
        bntSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntSave.setIconTextGap(0);
        bntSave.setPreferredSize(new java.awt.Dimension(80, 70));
        bntSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bntSaveMouseReleased(evt);
            }
        });
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        bntDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntDisplay.setText("แสดงรายการ");
        bntDisplay.setFocusable(false);
        bntDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntDisplay.setIconTextGap(0);
        bntDisplay.setPreferredSize(new java.awt.Dimension(90, 70));
        bntDisplay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bntDisplayMouseReleased(evt);
            }
        });
        bntDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDisplayActionPerformed(evt);
            }
        });

        bntExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntExit.setText("ออก(Exit)");
        bntExit.setFocusable(false);
        bntExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntExit.setIconTextGap(0);
        bntExit.setPreferredSize(new java.awt.Dimension(80, 70));
        bntExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bntExitMouseReleased(evt);
            }
        });

        jMenu1.setText("Function");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem1.setText("ยกเลิกการแก้ไข (Cancel Edit)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem2.setText("บันทึกข้อมูล (Save/Update)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem3.setText("ลบข้อมูล (Delete/Remove)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem4.setText("ออกจากการทำงาน (Exit)");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bntCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntSave, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bntCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(bntSave, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bntExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(bntDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(549, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void bntExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntExitMouseReleased
    bntExitClick();
}//GEN-LAST:event_bntExitMouseReleased

private void M_CodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_CodeKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        sp_codeExit();
    } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
        bntDisplayClick();
    }
}//GEN-LAST:event_M_CodeKeyPressed

private void bntCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelMouseReleased
    ClearVariable();
}//GEN-LAST:event_bntCancelMouseReleased

private void bntSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSaveMouseReleased
}//GEN-LAST:event_bntSaveMouseReleased

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    ClearVariable();
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    bntSaveClick();
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    bntRemoveClick();
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    bntExitClick();
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void bntDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDisplayMouseReleased
    //bntDisplayClick();
}//GEN-LAST:event_bntDisplayMouseReleased

private void bntDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDisplayActionPerformed
    bntDisplayClick();
}//GEN-LAST:event_bntDisplayActionPerformed

private void M_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_NameKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Brithday.requestFocus();
    }
}//GEN-LAST:event_M_NameKeyPressed

private void M_BrithdayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_BrithdayKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Begin.requestFocus();
    }
}//GEN-LAST:event_M_BrithdayKeyPressed

private void M_EndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_EndKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_HomeTel.requestFocus();
    }
}//GEN-LAST:event_M_EndKeyPressed

private void M_HomeTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_HomeTelKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_OfficeTel.requestFocus();
    }
}//GEN-LAST:event_M_HomeTelKeyPressed

private void M_OfficeTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_OfficeTelKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Mobile.requestFocus();
    }
}//GEN-LAST:event_M_OfficeTelKeyPressed

private void M_Reamrk1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_Reamrk1KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Remark2.requestFocus();
    }
}//GEN-LAST:event_M_Reamrk1KeyPressed

private void M_MobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_MobileKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Reamrk1.requestFocus();
    }
}//GEN-LAST:event_M_MobileKeyPressed

private void M_Remark2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_Remark2KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Name.requestFocus();
    }
}//GEN-LAST:event_M_Remark2KeyPressed

private void cmdDateChoose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDateChoose2ActionPerformed

    Point point = M_Begin.getLocationOnScreen();
    point.setLocation(point.getX(), point.getY());
    util.DateChooseDialog dcd = new util.DateChooseDialog(new java.awt.Frame(), true, point);
    dcd.setVisible(true);
    //dcd.showDialog(new LookAndFeelFrame(), true, point);
    M_Begin.setText(ShowDatefmt.format(dcd.getSelectDate().getTime()));
    ProcessEndDate();
    M_Begin.requestFocus();

}//GEN-LAST:event_cmdDateChoose2ActionPerformed

private void cmdDateChoose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDateChoose1ActionPerformed
    // TODO add your handling code here:
    Point point = M_Brithday.getLocationOnScreen();
    point.setLocation(point.getX(), point.getY());
    util.DateChooseDialog dcd = new util.DateChooseDialog(new java.awt.Frame(), true, point);
    dcd.setVisible(true);
    //dcd.showDialog(new LookAndFeelFrame(), true, point);
    M_Brithday.setText(ShowDatefmt.format(dcd.getSelectDate().getTime()));
    M_Brithday.requestFocus();
}//GEN-LAST:event_cmdDateChoose1ActionPerformed

private void cmdDateChoose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDateChoose3ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cmdDateChoose3ActionPerformed

private void M_BeginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_BeginKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_HomeTel.requestFocus();
    }
}//GEN-LAST:event_M_BeginKeyPressed

private void M_BeginInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_M_BeginInputMethodTextChanged
    // TODO add your handling code here:
}//GEN-LAST:event_M_BeginInputMethodTextChanged

private void M_BeginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_M_BeginFocusLost
    // TODO add your handling code here:
    ProcessEndDate();
}//GEN-LAST:event_M_BeginFocusLost

private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
    // TODO add your handling code here:
    ProcessEndDate();
    bntSaveClick();
}//GEN-LAST:event_bntSaveActionPerformed

private void M_BeginHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_M_BeginHierarchyChanged
    // TODO add your handling code here:
}//GEN-LAST:event_M_BeginHierarchyChanged

private void bntCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_bntCancelActionPerformed

private void M_BarcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_M_BarcodeFocusLost
    // TODO add your handling code here:
    M_BarcodeExit() ;
}//GEN-LAST:event_M_BarcodeFocusLost

private void M_BarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_M_BarcodeKeyPressed
    // TODO add your handling code here:
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        M_Name.requestFocus();
    }
}//GEN-LAST:event_M_BarcodeKeyPressed
public void M_BarcodeExit() {
   


}
public void ProcessEndDate() {
        Date TempDate1 = new Date();
        int intday;
        String TempYear;
        String TempDate;
        String TempMonth;
        try {
            TempDate1 = ShowDatefmt.parse(M_Begin.getText());
            TempYear = GetYear.format(TempDate1);
            TempDate = GetDate.format(TempDate1);
            TempMonth = GetMonth.format(TempDate1);
            int newYear = (Integer.parseInt(TempYear)) + 2;
            M_End.setText(TempDate + "/" + TempMonth + "/" + newYear);
            Calendar cal = PUtility.StrToCalendar(M_End.getText());
            cal.set(Calendar.DAY_OF_MONTH, DateUtilities.getMaxDay((GregorianCalendar) cal));
            intday = DateUtilities.getMaxDay((GregorianCalendar) cal);
            TempDate = DayFmt.format(intday);
            M_End.setText(TempDate + "/" + TempMonth + "/" + newYear);
            Calendar cal2 = Calendar.getInstance();
            cal2.setTime(TempDate1);
            cal2.add(Calendar.DAY_OF_MONTH, 44);
            M_NewEnd.setText("วันที่หมดอายุบัตรชั่วคราว : " + ShowDatefmt.format(cal2.getTime()));
        } catch (Exception e) {
        }

    }

    public void bntDisplayClick() {
        ClearVariable();
        FindMember frm = new FindMember(null, true);
        frm.setVisible(true);
        if (!PublicVar.ReturnString.equals("")) {
            M_Code.setText(PublicVar.ReturnString);
            sp_codeExit();
        }
    }

    public Boolean ChkValidDate() {
        Boolean RetVal = true;

        if (!PUtility.ChkDate(M_Brithday.getText())) {
            M_Brithday.requestFocus();
            RetVal = false;
        }
        if (!PUtility.ChkDate(M_Begin.getText())) {
            M_Begin.requestFocus();
            RetVal = false;
        }
        if (!PUtility.ChkDate(M_End.getText())) {
            M_End.requestFocus();
            RetVal = false;
        }

        if (M_Name.getText().length() == 0) {
            PUtility.ShowMsg("กรุณาป้อนชื่อสมาชิก...");
            M_Name.requestFocus();
            RetVal = false;
        }
        if (M_HomeTel.getText().length() == 0&&M_OfficeTel.getText().length() == 0&&M_Mobile.getText().length() == 0) {
            PUtility.ShowMsg("กรุณาป้อนเบอร์โทรศัพท์สมาชิกอย่างน้อย 1 หมายเลข...");
            M_HomeTel.requestFocus();
            RetVal = false;
        }
        String TempCode = M_Code.getText();
        char[] pass = M_Barcode.getPassword();
        String TempBarCode = "";
        for (int i = 0; i < pass.length; i++) {
            TempBarCode = TempBarCode + pass[i];
        }
        if ((TempCode.length()>0) && (!M_Code.getText().equals(""))) {
        if ((TempBarCode.length() == 13)) {
            String TMemCode = TempBarCode.substring(5, 12);
            if (TMemCode.equals(M_Code.getText())) {
                if (!PUtility.CheckEAN13Format(TempCode)) {
                    MSG.WAR_MSG(this, "รูปแบบรหัสบาร์โค๊ดไม่ถูกต้อง...");
                    M_Barcode.requestFocus();
                    RetVal = false ;
                }
            } else {
                MSG.WAR_MSG(this, "รูปแบบรหัสบาร์โค๊ดไม่ถูกต้อง...");
                M_Barcode.requestFocus();
                RetVal = false ;
            }
        } else {
            //PUtility.ShowMsg("รูปแบบรหัสบาร์โค๊ดไม่ถูกต้อง...");
            MSG.WAR_MSG(this, "รูปแบบรหัสบาร์โค๊ดไม่ถูกต้อง...");
            M_Barcode.requestFocus();
             RetVal = false ;
        }
    } else {
        MSG.WAR_MSG(this, "รูปแบบรหัสบาร์โค๊ดไม่ถูกต้อง...");
        M_Barcode.requestFocus();
        RetVal = false ;

    }
        return RetVal;
    }

    public void bntRemoveClick() {
        String TempCode = M_Code.getText();
        if (!TempCode.equals("")) {
            if (PUtility.ShowConfirmMsg("ยืนยันการลบข้อมูลสมาชิก รายการนี้ ?")) {
                try {
                    Statement stmt =  MySQLConnect.con.createStatement();
                    String SQLQuery = "delete from memmaster where m_code='" + TempCode + "'";
                    stmt.executeUpdate(SQLQuery);
                    stmt.close();
                } catch (SQLException e) {
                    PUtility.showError(e.getMessage());
                }
                ClearVariable();
            }
        }
    }

    public void bntSaveClick() {
        String TempCode = M_Code.getText();
        char[] pass = M_Barcode.getPassword();
        String TempBarCode = "";
        for (int i = 0; i < pass.length; i++) {
            TempBarCode = TempBarCode + pass[i];
        }
        Date TempDate1 = new Date();
        Date TempDate2 = new Date();
        Date TempDate3 = new Date();
        if (!TempCode.equals("")) {
            if (ChkValidDate()) {
                try {
                    TempDate1 = ShowDatefmt.parse(M_Brithday.getText());
                    TempDate2 = ShowDatefmt.parse(M_Begin.getText());
                    TempDate3 = ShowDatefmt.parse(M_End.getText());

                } catch (Exception e) {
                }
                if (SeekMember(TempCode)) {
                    try {
                        Statement stmt =  MySQLConnect.con.createStatement();
                        String SQLQuery = "update memmaster set m_name='" + M_Name.getText() + "',"
                                + "m_brid='" + Datefmt.format(TempDate1) + "',"
                                + "m_begin='" + Datefmt.format(TempDate2) + "',"
                                + "m_end='" + Datefmt.format(TempDate3) + "',"
                                + "m_tel='" + M_HomeTel.getText() + "',"
                                + "m_office='" + M_OfficeTel.getText() + "',"
                                + "m_rem1='" + M_Reamrk1.getText() + "',"
                                + "m_mobile='" + M_Mobile.getText() + "',"
                                + "m_rem2='" + M_Remark2.getText() + "'"
                                + "m_barcode='" + TempBarCode + "'"
                                + " where m_code='" + TempCode + "'";
                        stmt.executeUpdate(SQLQuery);
                        stmt.close();
                    } catch (SQLException e) {
                        MSG.ERR_MSG(this, e.getMessage());
                    }
                    ClearVariable();
                } else {
                    try {
                        Statement stmt =  MySQLConnect.con.createStatement();
                        String SQLQuery = "insert into memmaster (m_code,m_bran,m_barcode,m_type,m_name,m_card,m_sex,m_status,"
                                + "m_brid,m_begin,m_end,m_nation,m_occu,m_incom,m_company,m_email,m_addr1,m_addr2,m_addr3,"
                                + "m_addr4,m_addr5,m_addr6,m_post,m_tel,m_fax,m_wise,m_chai,m_food,m_rem1,m_rem2,m_last,m_sum,"
                                + "m_discrate,m_mobile,m_office) "
                                + "values ('" + M_Code.getText() + "',"
                                + "'" + PublicVar.Branch_Code + "',"
                                + "'" + TempBarCode + "',"
                                + "'',"
                                + "'" + M_Name.getText() + "',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'" + Datefmt.format(TempDate1) + "',"
                                + "'" + Datefmt.format(TempDate2) + "',"
                                + "'" + Datefmt.format(TempDate3) + "',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'',"
                                + "'" + M_HomeTel.getText() + "',"
                                + "'',"
                                + "'',"
                                + "0,"
                                + "'',"
                                + "'" + M_Reamrk1.getText() + "',"
                                + "'" + M_Remark2.getText() + "',"
                                + "'" + Datefmt.format(date) + "',"
                                + "0,"
                                + "'',"
                                + "'" + M_Mobile.getText() + "',"
                                + "'" + M_OfficeTel.getText() + "')";
                        stmt.executeUpdate(SQLQuery);
                        stmt.close();
                    } catch (SQLException e) {
                        MSG.ERR_MSG(this, e.getMessage());
                    }
                    ClearVariable();
                }
            }
        }

    }

    public void ClearVariable() {
        AddNew = true ;
        M_Code.setText("");
        M_Barcode.setText("") ;
        M_Name.setText("");
        M_Brithday.setText("");
        M_Begin.setText("");
        M_End.setText("");
        M_HomeTel.setText("");
        M_OfficeTel.setText("");
        M_Mobile.setText("");
        M_Reamrk1.setText("");
        M_Remark2.setText("");
        M_Code.setFocusable(true);
        M_Name.setFocusable(false);
        M_Brithday.setFocusable(false);
        M_Begin.setFocusable(false);
        M_End.setFocusable(false);
        M_HomeTel.setFocusable(false);
        M_Mobile.setFocusable(false);
        M_OfficeTel.setFocusable(false);
        M_Reamrk1.setFocusable(false);
        M_Remark2.setFocusable(false);
        M_NewEnd.setText("");
        ProcessStr.setText("");
        M_Code.requestFocus();
    }

    public void sp_codeExit() {
        String TempCode = M_Code.getText();
        if (!TempCode.equals("")) {
            if ((M_Code.getText().length() == 7) || (M_Code.getText().length() == 13)) {
                try {
                    if (M_Code.getText().length() == 13) {
                        TempCode = TempCode.substring(5, 12);
                        M_Code.setText(TempCode);
                    }
                    Statement stmt =  MySQLConnect.con.createStatement();
                    String SQLQuery = "Select *from memmaster where m_code='" + TempCode + "'";
                    ResultSet rec = stmt.executeQuery(SQLQuery);
                    rec.first();
                    if (rec.getRow() == 0) {
                        Calendar cal = Calendar.getInstance();
                        cal.add(Calendar.DAY_OF_MONTH, 44);
                        M_Brithday.setText(ShowDatefmt.format(cal.getTime()));
                        M_Begin.setText(ShowDatefmt.format(date));
                        String TempYear = GetYear.format(date);
                        String TempMonth = GetMonth.format(date);
                        String TempDate = GetDate.format(date) ;
                        int newYear = (Integer.parseInt(TempYear)) + 2;
                        //TempYear = newYear.
                        M_End.setText(TempDate + "/" + TempMonth + "/" + newYear);
                        Calendar cal2 = PUtility.StrToCalendar(M_End.getText());
                        cal2.set(Calendar.DAY_OF_MONTH, DateUtilities.getMaxDay((GregorianCalendar) cal));
                        int intday = DateUtilities.getMaxDay((GregorianCalendar) cal);
                        TempDate = DayFmt.format(intday);
                        M_End.setText(TempDate + "/" + TempMonth + "/" + newYear);
                        
                        M_NewEnd.setText("วันที่หมดอายุบัตรชั่วคราว : " + ShowDatefmt.format(cal.getTime()));
                        ProcessStr.setText("เพิ่มข้อมูลใหม่...");
                        AddNew = true ;
                        M_Barcode.setEnabled(true) ;
                        GetDataValue();
                        M_Barcode.requestFocus();
                    } else {
                        if (rec.getString("m_active").equals("Y")) {
                            M_Name.setText(rec.getString("m_name"));
                            M_Barcode.setText(rec.getString("m_barcode")) ;
                            M_Brithday.setText(ShowDatefmt.format(rec.getDate("m_brid")));
                            M_Begin.setText(ShowDatefmt.format(rec.getDate("m_begin")));
                            M_End.setText(ShowDatefmt.format(rec.getDate("m_end")));
                            M_HomeTel.setText(rec.getString("m_tel"));
                            M_OfficeTel.setText(rec.getString("m_office"));
                            M_Mobile.setText(rec.getString("m_mobile"));
                            M_Reamrk1.setText(rec.getString("m_rem1"));
                            M_Remark2.setText(rec.getString("m_rem2"));
                            Calendar cal = Calendar.getInstance();
                            cal.setTime(rec.getDate("m_begin"));
                            cal.add(Calendar.DAY_OF_MONTH, 44);
                            M_NewEnd.setText("วันที่หมดอายุบัตรชั่วคราว : " + ShowDatefmt.format(cal.getTime()));
                            ProcessStr.setText("แก้ข้อมูลเก่า...");
                            M_Barcode.setEnabled(false) ;
                            AddNew = false ;
                            GetDataValue();
                            M_Name.requestFocus();
                        } else {
                            PUtility.ShowMsg("รหัสสมาชิกท่านนี้ได้ถูกยกเลิกการใช้งานแล้ว...โดยฝ่ายประชาสัมพันธ์ !!!");
                            ClearVariable();
                        }
                    }
                    rec.close();
                    stmt.close();
                } catch (SQLException e) {
                    MSG.ERR_MSG(this, e.getMessage());
                }

            } else {
                MSG.WAR_MSG(this, "รหัสสมาชิกต้องมีขนาด 7 หลักเท่านั้น...");
                ClearVariable();
            }

        }

    }

    public Boolean SeekMember(String TempCode) {
        Boolean RetVal = false;
        try {
            Statement stmt =  MySQLConnect.con.createStatement();
            String SQLQuery = "Select *from memmaster where m_code='" + TempCode + "'";
            ResultSet rec = stmt.executeQuery(SQLQuery);
            rec.first();
            if (rec.getRow() == 0) {
                RetVal = false;
            } else {
                RetVal = true;
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            PUtility.showError(e.getMessage());
        }
        return RetVal;
    }

    public void GetDataValue() {
        M_Code.setFocusable(false);
        M_Name.setFocusable(true);
        M_Brithday.setFocusable(true);
        M_Begin.setFocusable(true);
        M_End.setFocusable(true);
        M_HomeTel.setFocusable(true);
        M_Mobile.setFocusable(true);
        M_OfficeTel.setFocusable(true);
        M_Reamrk1.setFocusable(true);
        M_Remark2.setFocusable(true);
    }

    public void bntExitClick() {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddNewArCustomer dialog = new AddNewArCustomer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField M_Barcode;
    private javax.swing.JFormattedTextField M_Begin;
    private javax.swing.JFormattedTextField M_Brithday;
    private javax.swing.JTextField M_Code;
    private javax.swing.JFormattedTextField M_End;
    private javax.swing.JTextField M_HomeTel;
    private javax.swing.JTextField M_Mobile;
    private javax.swing.JTextField M_Name;
    private javax.swing.JLabel M_NewEnd;
    private javax.swing.JTextField M_OfficeTel;
    private javax.swing.JTextField M_Reamrk1;
    private javax.swing.JTextField M_Remark2;
    private javax.swing.JLabel ProcessStr;
    private javax.swing.JButton bntCancel;
    private javax.swing.JButton bntDisplay;
    private javax.swing.JButton bntExit;
    private javax.swing.JButton bntSave;
    private javax.swing.JButton cmdDateChoose1;
    private javax.swing.JButton cmdDateChoose2;
    private javax.swing.JButton cmdDateChoose3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
