package program;

import printReport.PPrint;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import database.MySQLConnect;
import java.sql.Statement;
import util.MSG;

public class CopyBill extends javax.swing.JDialog {

    Date date = new Date();
    TranRecord[] MyArray;
    int ArraySize;
    PPrint prn = new PPrint();
    CreditPaymentRec[] CreditArray;
    POSConfigSetup CONFIG;

    /** Creates new form CopyBill */
    public CopyBill(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PublicVar.SmpCouponArray = null ;
        CONFIG = POSConfigSetup.Bean();
        try {
            Statement stmt =  MySQLConnect.con.createStatement();
            String SqlQuery = "select *from billno where b_macno='" + Value.MACNO + "'";
            ResultSet rec = stmt.executeQuery(SqlQuery);
            rec.last();
            if (rec.getRow() == 0) {
            } else {
                do {
                    txtBillNo.setText(rec.getString("b_refno"));
                } while (rec.next());
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            PUtility.showError(e.getMessage());
        }
        txtCopy.setText(Integer.toString(CONFIG.getP_BillCopy()));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBillNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCopy = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bntOK = new javax.swing.JButton();
        bntExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("พิมพ์สำเนาใบเสร็จรับเงิน");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("กรุณาป้อนเลขที่บิล และจำนวน Copy ที่ต้องการ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("เลขที่บิล (Receipt No)");

        txtBillNo.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        txtBillNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillNoActionPerformed(evt);
            }
        });
        txtBillNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBillNoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("จำนวน Copy");

        txtCopy.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCopy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCopy.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        txtCopy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCopyKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setText("CE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setText("/");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setText("*");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("Enter");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("9");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("8");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("4");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("6");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("3");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("2");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton15.setText("0");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton16.setText(".");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton17.setText("+");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bntOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntOK.setText("F5-ตกลง (OK)");
        bntOK.setFocusable(false);
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        bntExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntExit.setText("ESC-ออก (Exit)");
        bntExit.setFocusable(false);
        bntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(536, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtBillNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtBillNoActionPerformed

private void txtBillNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBillNoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        txtCopy.requestFocus();
    }
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    }
    if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }

}//GEN-LAST:event_txtBillNoKeyPressed

private void txtCopyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopyKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick();
    }else if (evt.getKeyCode() == KeyEvent.VK_F5) {
        bntOKClick();
    }
}//GEN-LAST:event_txtCopyKeyPressed

    private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
        bntOKClick();
    }//GEN-LAST:event_bntOKActionPerformed

    private void bntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExitActionPerformed
        bntExitClick();
    }//GEN-LAST:event_bntExitActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        input("/");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        input("*");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        input("-");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        input("9");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        input("8");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        input("7");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        input("4");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        input("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        input("6");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        input("3");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        input("2");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        input("1");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        input("0");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        input(".");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        input("+");
    }//GEN-LAST:event_jButton17ActionPerformed

    public void Action() {
        int CopyPrn = Integer.parseInt(txtCopy.getText());
        String BillNo = txtBillNo.getText();
        //Load Data From BillNo
        int billcopy = 0;
        try {
            Statement stmt =  MySQLConnect.con.createStatement();
            String SqlQuery = "select *from billno where (b_macno='" + Value.MACNO + "') and (b_refno='" + BillNo + "')";
            ResultSet rec = stmt.executeQuery(SqlQuery);
            rec.first();
            if (rec.getRow() == 0) {
                MSG.ERR(this, "ไม่พบใบเสร็จรับเงินเลขที่ "+txtBillNo.getText()+"  ในฐานข้อมูล...") ;
                txtBillNo.selectAll() ;
                txtBillNo.requestFocus();
            } else {
                ProcessCopyBill() ;
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            PUtility.showError(e.getMessage());
        }
    }
    public void bntOKClick() {
        Action() ;
    }
    public void ProcessCopyBill() {
        int CopyPrn = Integer.parseInt(txtCopy.getText());
        String BillNo = txtBillNo.getText();
        //Load Data From BillNo
        int billcopy = 0;
        try {
            Statement stmt =  MySQLConnect.con.createStatement();
            String SqlQuery = "select *from billno where (b_macno='" + Value.MACNO + "') and (b_refno='" + BillNo + "')";
            ResultSet rec = stmt.executeQuery(SqlQuery);
            rec.first();
            if (rec.getRow() == 0) {
                PUtility.ShowMsg("ไม่พบใบเสร็จรับเงินเลขที่ "+txtBillNo.getText()+"  ในฐานข้อมูล...");
                this.dispose();
            } else {
                PublicVar.TableRec_RefNo = rec.getString("b_refno");
                PublicVar.TableRec_OnDate = rec.getDate("b_ondate");
                PublicVar.TableRec_OnTime = rec.getString("b_ontime");
                PublicVar.TableRec_TCode = rec.getString("b_table");
                PublicVar.TableRec_MacNo = rec.getString("b_macno");
                PublicVar.TableRec_Cashier = rec.getString("b_cashier");
                PublicVar.TableRec_TLogInTime = "";
                PublicVar.TableRec_TCurTime = "";
                PublicVar.TableRec_TLoginDate = date;
                PublicVar.TableRec_TOnAct = "";
                PublicVar.TableRec_TCustomer = rec.getInt("b_cust");
                PublicVar.TableRec_ETD = rec.getString("b_etd");
                PublicVar.TableRec_TAmount = rec.getDouble("b_total");
                PublicVar.TableRec_Food = rec.getDouble("b_food");
                PublicVar.TableRec_Drink = rec.getDouble("b_drink");
                PublicVar.TableRec_Product = rec.getDouble("b_product");
                PublicVar.TableRec_Service = rec.getDouble("b_service");
                PublicVar.TableRec_ServiceAmt = rec.getDouble("b_serviceamt");
                PublicVar.TableRec_FastDisc = rec.getString("b_fastdisc");
                PublicVar.TableRec_FastDiscAmt = rec.getDouble("b_fastdiscamt");
                PublicVar.TableRec_EmpDisc = rec.getString("b_empdisc");
                PublicVar.TableRec_EmpDiscAmt = rec.getDouble("b_empdiscamt");
                PublicVar.TableRec_TrainDisc = rec.getString("b_traindisc");
                PublicVar.TableRec_TrainDiscAmt = rec.getDouble("b_traindiscamt");
                PublicVar.TableRec_MemDisc = rec.getString("b_memdisc");
                PublicVar.TableRec_MemDiscAmt = rec.getDouble("b_memdiscamt");
                PublicVar.TableRec_SubDisc = rec.getString("b_subdisc");
                PublicVar.TableRec_SubDiscAmt = rec.getDouble("b_subdiscamt");
                PublicVar.TableRec_DiscBath = rec.getDouble("b_subdiscbath");
                PublicVar.TableRec_ProDiscAmt = rec.getDouble("b_prodiscamt");
                PublicVar.TableRec_SpaDiscAmt = rec.getDouble("b_spadiscamt");
                PublicVar.TableRec_CuponDiscAmt = rec.getDouble("b_cupondiscamt");
                PublicVar.TableRec_ItemDiscAmt = rec.getDouble("b_itemdiscamt");
                PublicVar.TableRec_MemCode = rec.getString("b_memcode");
                PublicVar.TableRec_MemName = rec.getString("b_memname");
                PublicVar.TableRec_MemBegin = null;
                PublicVar.TableRec_MemEnd = null;
                PublicVar.TableRec_MemBrid = null;
                PublicVar.TableRec_MemCurAmt = rec.getDouble("b_sumscore");
                PublicVar.TableRec_Score = rec.getDouble("b_memcursum");
                PublicVar.TableRec_SumScoreal = rec.getDouble("b_sumscore");
                //PublicVar.TableRec_MemLastDate = rec.getString("b_mlsv");
                PublicVar.TableRec_NetTotal = rec.getDouble("b_nettotal");
                PublicVar.TableRec_NetFood = rec.getDouble("b_netfood");
                PublicVar.TableRec_NetDrink = rec.getDouble("b_netdrink");
                PublicVar.TableRec_NetProduct = rec.getDouble("b_netproduct");
                PublicVar.TableRec_NetVat = rec.getDouble("b_netvat");
                PublicVar.TableRec_NetNonVat = rec.getDouble("b_netnonvat");
                PublicVar.TableRec_Vat = rec.getDouble("b_vat");
                PublicVar.TableRec_ArCode = rec.getString("b_accrcode");
                PublicVar.TableRec_AccrCr = rec.getInt("b_accrcr");
                PublicVar.TableRec_ArPayment = rec.getDouble("b_accramt");
                PublicVar.TableRec_PayAmt = rec.getDouble("b_payamt");
                PublicVar.TableRec_Ton = rec.getDouble("b_ton");
                PublicVar.TableRec_Earnest = rec.getDouble("b_earnest");
                PublicVar.TableRec_Gift_Voucher = rec.getDouble("b_giftvoucher");
                PublicVar.TableRec_Cash = rec.getDouble("b_cash");
                PublicVar.TableRec_Cr_Bank = rec.getString("b_crbank");   //For SMP

                PublicVar.TableRec_Cr_CardAmt = rec.getDouble("b_crcardamt");
                PublicVar.TableRec_Cr_CurPoint = rec.getInt("b_crcurpoint");
                PublicVar.TableRec_Cr_SumPoint = rec.getInt("b_crsumpoint");
//                PublicVar.TableRec_Cr_PurseAmt = rec.getDouble("b_crpurseamt");
//                PublicVar.TableRec_Cr_CouponAmt = rec.getDouble("b_crcouponamt");
//                PublicVar.TableRec_Cr_TotCoupon = rec.getDouble("b_crtotcoupon");
//                PublicVar.TableRec_Cr_Code1 = rec.getString("b_crcode1");
                PublicVar.TableRec_Cr_Name1 = "";
                PublicVar.TableRec_Cr_Charge = rec.getDouble("b_crcharge1");
                PublicVar.TableRec_Cr_ChargeAmt = rec.getDouble("b_crchargeamt1");
                PublicVar.TableRec_Cr_Redule = 0.00;
                PublicVar.TableRec_Cr_CardNo1 = rec.getString("b_cardno1");
                PublicVar.TableRec_Cr_App_Code1 = rec.getString("b_appcode1");
                PublicVar.TableRec_Cr_Amount1 = rec.getDouble("b_cramt1");
                PublicVar.TableRec_PrintTotal = 0.00;
                PublicVar.TableRec_PrnCnt = 0;
                PublicVar.TableRec_BillCopy = 0;
                PublicVar.TableRec_PrnTime1 = "";
                PublicVar.TableRec_PrnTime2 = "";
                PublicVar.TableRec_BranCode = rec.getString("b_bran");
                PublicVar.TableRec_BranName = rec.getString("b_branname");
                PublicVar.TableRec_BranTel = rec.getString("b_tel");
//                PublicVar.TableRec_BranchDate = rec.getString("b_recdate") ;
                PublicVar.TableRec_BranTime = rec.getString("b_rectime");
//                PublicVar.TableRec_BarcodeLost= rec.getString("barcodelost");
//                PublicVar.TableRec_BarcodeLostUser= rec.getString("barcodelostuser") ;
//                PublicVar.TableRec_BarcodeLostUserName= rec.getString("barcodelostusername") ;
//                PublicVar.TableRec_BarcodeLostTime= rec.getString("barcodelosttime") ;
//                PublicVar.TableRec_EmpCode =  rec.getString("employcode");
//                PublicVar.TableRec_EmpName =  rec.getString("employname");
                billcopy = rec.getInt("b_billcopy");
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            PUtility.showError(e.getMessage());
        }
        //Load Data From Balance
        try {
            Statement stmt =  MySQLConnect.con.createStatement();
            String LoadBalance = "select *from t_sale where (macno='" + Value.MACNO + "') and (r_refno='" + BillNo + "')";
            ResultSet rec = stmt.executeQuery(LoadBalance);
            Date dt = new Date();
            PublicVar.P_ItemCount = 0;
            MyArray = null;
            MyArray = new TranRecord[1];
            rec.first();
            if (rec.getRow() == 0) {
            } else {
                do {
                    PublicVar.P_ItemCount++;
                    TranRecord TranRec = new TranRecord();
                    TranRec.R_Index = rec.getString("r_index");
                    TranRec.R_Date = rec.getDate("r_date");
                    TranRec.R_Table = rec.getString("r_table");
                    TranRec.R_Time = rec.getString("r_time");
                    TranRec.Macno = rec.getString("macno");
                    TranRec.Cashier = rec.getString("cashier");
                    TranRec.R_Emp = rec.getString("r_emp");
                    TranRec.R_Set = rec.getString("r_set");
                    TranRec.R_Stock = rec.getString("r_stock");
                    TranRec.R_PluCode = rec.getString("r_plucode");
                    TranRec.R_PName = rec.getString("r_pname");
                    TranRec.R_Unit = rec.getString("r_unit");
                    TranRec.R_Group = rec.getString("r_group");
                    TranRec.R_Status = rec.getString("r_status");
                    TranRec.R_Normal = rec.getString("r_normal");
                    TranRec.R_Discount = rec.getString("r_discount");
                    TranRec.R_Service = rec.getString("r_service");
                    TranRec.R_Vat = rec.getString("r_vat");
                    TranRec.R_Type = rec.getString("r_type");
                    TranRec.R_ETD = rec.getString("r_etd");
                    TranRec.R_Quan = rec.getDouble("r_quan");
                    TranRec.R_Price = rec.getDouble("r_price");
                    TranRec.R_Total = rec.getDouble("r_total");
                    TranRec.R_PrType = rec.getString("r_prtype");
                    TranRec.R_PrCode = rec.getString("r_prcode");
                    TranRec.R_PrDisc = rec.getDouble("r_prdisc");
                    TranRec.R_PrBath = rec.getDouble("r_prbath");
                    TranRec.R_PrAmt = rec.getDouble("r_pramt");
                    TranRec.R_PrQuan = rec.getDouble("r_prquan");
                    TranRec.R_Redule = rec.getDouble("r_redule");
                    TranRec.R_KIC = rec.getString("r_kic");
                    TranRec.R_KicPrint = rec.getString("r_kicprint");
                    TranRec.R_Void = rec.getString("r_void");
                    TranRec.R_VoidUser = rec.getString("r_voiduser");
                    TranRec.R_VoidTime = rec.getString("r_voidtime");
                    TranRec.R_DiscBath = rec.getDouble("r_discbath");
                    if (PublicVar.P_ItemCount > 1) {
                        MyArray = PUtility.addArray(MyArray);
                    }
                    ArraySize = MyArray.length;
                    MyArray[ArraySize - 1] = TranRec;
                } while (rec.next());
            }
            rec.close();
            stmt.close();

        } catch (SQLException e) {
            PUtility.showError(e.getMessage());
        }
        if (CONFIG.getP_BillCopyOne().equals("Y") & (billcopy > 0)) {
            PUtility.ShowMsg("บิลเลขที่ " + BillNo + "  ได้มีการพิมพ์สำเนาไปแล้ว...ไม่สามารถพิมพ์ได้อีก");
            txtBillNo.requestFocus();
        } else {
            if (CopyPrn > CONFIG.getP_BillCopy()) {
                CopyPrn = CONFIG.getP_BillCopy();
                txtCopy.setText(Integer.toString(CopyPrn));
            }
            for (int i = 1; i <= CopyPrn; i++) {
                prn.PrintBillCopy(MyArray, BillNo, i,CreditArray);
            }
            try {
                Statement stmt =  MySQLConnect.con.createStatement();
                String SqlQuery = "update billno set b_billcopy=b_billcopy+1 where (b_refno='" + BillNo + "') and (b_macno='" + Value.MACNO + "')";
                stmt.executeUpdate(SqlQuery);
                stmt.close();
            } catch (SQLException e) {
                PUtility.showError(e.getMessage());
            }
            this.dispose();
        }
        
    }

    public void inputfrombnt(String str) {
        String tempstr;
        if (txtBillNo.hasFocus()) {
            tempstr = txtBillNo.getText();
            tempstr = tempstr + str;
            txtBillNo.setText(tempstr);
        }
        if (txtCopy.hasFocus()) {
            tempstr = txtCopy.getText();
            tempstr = tempstr + str;
            txtCopy.setText(tempstr);
        }
    }

    public void bntExitClick() {
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new  

              Runnable() {

                      public void run() {
                CopyBill dialog = new CopyBill(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new  

                      java.awt.event.WindowAdapter  
                        () {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExit;
    private javax.swing.JButton bntOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtBillNo;
    private javax.swing.JFormattedTextField txtCopy;
    // End of variables declaration//GEN-END:variables

    private void input(String string) {
        
    }
}
