package program;
import java.sql.Time;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

public class PublicVar {

    public static ArrayList<SmpCoupon> SmpCouponArray;
    public static String UseTouchScreen;
    public static TranRecord KicRec;
    public static String ProcessType;
    public static UserRecord TUserRec;
    public static UserRecord BarcodeLostUserRec;
    public static UserRecord supUserRec;
    public static UserRecord TempUserRec;
    public static UserRecord TSupervisorRec;
    public static Boolean ChangTypeOK;
    public static TranRecord[] ChangTypeArray;
    public static TranRecord[] TempMyArray;
    public static CouponDetailRec[] TempCuDetailArray;
    public static TranRecord[] TempMyArray2;
    public static SimpleDateFormat DateFmt = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    public static SimpleDateFormat TimeFmt = new SimpleDateFormat("HH:mm");
    public static int P_ItemCount = 0;
    public static Double P_TotalAmt = 0.00;
    public static Double P_TotService = 0.00;
    public static Double P_TotDiscount = 0.00;
    public static Double P_NetAmt = 0.00;
    public static int P_LineCount = 0;
    public static Boolean P_LogoffOK = false;
    public static String PrintOK = "Y";
    public static String P_Code = "";
    public static String P_Status = "";
    public static double P_Qty = 0;
    public static Boolean ErrorColect = false;
    public static String ReturnString = "";
    public static int ReturnQty = 0;
    public static String TempIndexKey = "";
    public static int RowSelected = 0;
    public static boolean SubTotalOK;
    public static int CouponCnt = 0;
    public static String Open24House = "N";
    public static Date SaleDate;

    //ForCharge
    public static double ChargePriceDown = 0.50;
    public static String ChargeCode = "";
    public static String ChargeName = "";
    public static int ChargeType = 0;
    public static String ChargeRemark = "";
    public static String ChargeGroup = "";
    public static Date ChargeBeginDate;
    public static Date ChargeExpDate;
    public static String ChargeDocNo = "";

    //For ChkPromotion
    public static Double PDisc = 0.0;
    public static double PSpDisc = 0.0;
    public static String ProType = "";
    public static double XPoint;

    public static String Branch_Name = "";
    public static String Branch_Code = "";
    public static String Branch_BranchType = "";
    public static String Branch_Group = "";
    public static String Branch_charge = "";
    public static Date Branch_ChargeStart;
    public static Date Branch_ChargeExp;

    public static String Branch_Kic1 = "N";
    public static String Branch_Kic2 = "N";
    public static String Branch_Kic3 = "N";
    public static String Branch_Kic4 = "N";
    public static String Branch_Saveorder = "N";
    public static String Branch_GiftStatusChk = "N";
    public static String Branch_PromotionGP = "";
    public static int LockTime = 0;

    public static String MacNo = "";
    public static String invoiceno = "XXXXXXXX";
    public static String CheckStockOnLine = "N";

    public static String _User = "";
    public static int _UserRound = 1;
    public static String _RealUser = "";
    public static String _Password = "";
    public static String _UserName = "";
    public static String Cont0 = "N";
    public static String Cont1 = "N";
    public static String Cont2 = "N";
    public static String Cont3 = "N";
    public static String Cont4 = "N";
    public static String Cont5 = "N";
    public static String Cont6 = "N";
    public static String Cont7 = "N";
    public static String Cont8 = "N";
    public static String Cont9 = "N";
    public static String Cont10 = "N";
    public static String Cont11 = "N";
    public static String Cont12 = "N";
    public static String Cont13 = "N";
    public static String Cont14 = "N";
    public static String Cont15 = "N";
    public static String Sale1 = "N";
    public static String Sale2 = "N";
    public static String Sale3 = "N";
    public static String Sale4 = "N";
    public static String Sale5 = "N";
    public static String Sale6 = "N";
    public static String Sale7 = "N";
    public static String Sale8 = "N";
    public static String Sale9 = "N";
    public static String Sale10 = "N";
    public static String Sale11 = "N";
    public static String Sale12 = "N";
    public static String Sale13 = "N";
    public static String Sale14 = "N";
    public static String Sale15 = "N";
    public static String Sale16 = "N";
    public static String Sale17 = "N";
    public static String Sale18 = "N";
    public static String Sale19 = "N";
    public static String Sale20 = "N";
    public static String Sale21 = "N";
    public static String Sale22 = "N";
    public static String Sale23 = "N";
    public static String Sale24 = "N";
    public static String Sale25 = "N";
    public static String Sale26 = "N";
    public static String Sale27 = "N";
    public static String Sale28 = "N";
    public static String Sale29 = "N";
    public static String Sale30 = "N";
    public static String Sale31 = "N";
    public static String Sale32 = "N";
    public static String Sale33 = "N";
    public static String Sale34 = "N";
    public static String Sale35 = "N";
    public static String Sale36 = "N";
    public static String Stock0_1 = "N";
    public static String Stock1 = "N";
    public static String Stock2 = "N";
    public static String Stock3 = "N";
    public static String Stock4 = "N";
    public static String Stock5 = "N";
    public static String Stock6 = "N";
    public static String Stock7 = "N";
    public static String Stock8 = "N";
    public static String Stock9 = "N";
    public static String Stock10 = "N";
    public static String Stock11 = "N";
    public static String Stock12 = "N";
    public static String Stock13 = "N";
    public static String Stock14 = "N";
    public static String Stock15 = "N";
    public static String Stock16 = "N";
    public static String Stock17 = "N";
    public static String Stock18 = "N";
    public static String Stock19 = "N";
    public static String Stock20 = "N";
    public static String Stock21 = "N";
    public static String Stock22 = "N";
    public static String Stock23 = "N";
    public static String Stock24 = "N";
    public static String Stock25 = "N";
    public static String Stock26 = "N";
    public static String Stock27 = "N";
    public static String Stock28 = "N";
    public static String Stock29 = "N";
    public static String Stock30 = "N";
    public static String Stock31 = "N";
    public static String Stock32 = "N";
    public static String Stock33 = "N";
    public static String Stock34 = "N";
    public static String Stock35 = "N";
    public static String Stock36 = "N";
    public static String Stock37 = "N";
    public static String Stock38 = "N";
    public static String Stock39 = "N";
    public static String Stock40 = "N";
    public static String Stock41 = "N";
    public static String Stock42 = "N";
    public static String Stock43 = "N";
    public static String Stock44 = "N";
    public static String Stock45 = "N";
    public static String Stock46 = "N";
    public static String Stock47 = "N";
    public static String Stock48 = "N";
    public static String Stock49 = "N";
    public static String Stock50 = "N";
    public static String Stock51 = "N";
    public static String Stock52 = "N";
    public static String Stock53 = "N";
    public static String Stock54 = "N";
    public static String Stock55 = "N";
    public static String Stock56 = "N";
    public static String Stock57 = "N";

    //THWRec = Record No {Define Terminal Hardware Config....}
    public static String HWRec_Terminal = "";
    public static String HWrec_MacNo = "";
    public static long HWrec_Receno1 = 0;
    public static String HWrec_SaleType = "";
    public static String HWrec_Heading1 = "";
    public static String HWrec_Heading2 = "";
    public static String HWrec_Heading3 = "";
    public static String HWrec_Heading4 = "";
    public static String HWrec_Footting1 = "";
    public static String HWrec_Footting2 = "";
    public static String HWrec_DrPort = "";
    public static String HWrec_DrType = "";
    public static String HWrec_DrCom = "";
    public static String HWrec_DisPort = "";
    public static String HWrec_DisType = "";
    public static String HWrec_DisCom = "";
    public static String HWrec_PrnPort = "";
    public static String HWrec_PrnType = "1";
    public static String HWrec_PrnCom = "";
    public static String HWrec_PrnThaiLeval = "";
    public static String HWrec_Kic1Port = "";
    public static String HWrec_Kic1Type = "";
    public static String HWrec_Kic1Com = "";
    public static Boolean HWrec_Kic1ThaiLeval = false;
    public static String HWrec_Kic2Port = "";
    public static String HWrec_Kic2Type = "";
    public static String HWrec_Kic2Com = "";
    public static String HWrec_Kic2ThaiLeval = "";
    public static String HWrec_Kic3Port = "";
    public static String HWrec_Kic3Type = "";
    public static String HWrec_Kic3Com = "";
    public static Boolean Kic3ThaiLeval = false;
    public static String HWrec_Kic4Port = "";
    public static String HWrec_Kic4Type = "";
    public static String HWrec_Kic4Com = "";
    public static Boolean HWrec_Kic4ThaiLeval = false;
    public static String HWrec_EDCPort = "";
    public static String HWrec_SMPBank = "";
    public static String HWrec_SMPPort = "";
    public static String HWrec_MenuItemList = "";
    public static String HWRec_EJDailyPath = "";
    public static String HWRec_EJBackupPath = "";

    //TPOSConfig_Rec = Record     {Define POS-Default data Record...}
    public static String Posconfig_P_Terminal = "";
    public static Double Posconfig_P_Vat = 0.00;
    public static String Posconfig_P_VatType = "";
    public static Double Posconfig_P_Service = 0.00;
    public static String Posconfig_P_VatPrn = "";
    public static int Posconfig_P_BillCopy = 1;
    public static String Posconfig_P_CodePrn = "";
    public static String Posconfig_P_BillCopyOne = "";
    public static String Posconfig_P_DefaultSaleType = "";
    public static String Posconfig_P_EmpUse = "";
    public static String P_CheckBillBeforCash = "";
    public static String Posconfig_P_PrintDetailOnRecp = "";
    public static String Posconfig_P_PrintRecpMessage = "";

    public static String Posconfig_P_MemDisc = "";
    public static String Posconfig_P_MemDiscChk = "";
    public static String Posconfig_P_MemDiscGet = "";
    public static String Posconfig_P_MemDiscMax = "";

    public static String Posconfig_P_FastDisc = "";
    public static String Posconfig_P_FastDiscChk = "";
    public static String Posconfig_P_FastDiscGet = "";
    public static String Posconfig_P_FastDiscMax = "";

    public static String Posconfig_P_EmpDisc = "";
    public static String Posconfig_P_EmpDiscChk = "";
    public static String Posconfig_P_EmpDiscGet = "";
    public static String Posconfig_P_EmpDiscMax = "";

    public static String Posconfig_P_TrainDisc = "";
    public static String Posconfig_P_TrainDiscChk = "";
    public static String Posconfig_P_TrainDiscGet = "";
    public static String Posconfig_P_TrainDiscMax = "";

    public static String Posconfig_P_SubDisc = "";
    public static String Posconfig_P_SubDiscChk = "";
    public static String Posconfig_P_SubDiscGet = "";
    public static String Posconfig_P_SubDiscMax = "";

    public static String Posconfig_P_DiscBathChk = "";
    public static int Posconfig_P_DiscBathMax = 0;
    public static String Posconfig_P_PromotionChk = "";
    public static String Posconfig_P_SpacialChk = "";
    public static String Posconfig_P_DiscRound = "";
    public static String Posconfig_P_ServiceRound = "";
    public static String Posconfig_P_SerChkBySaleType = "";
    public static String Posconfig_P_DiscChkBySaleType = "";
    public static Double Posconfig_P_Memaddtimeamt = 0.0;
    public static Double Posconfig_P_Memaddtimescore = 0.0;

    //TTableRec = Record   {Table Record .......}
    public static String TableRec_RefNo = "";
    public static Date TableRec_OnDate;
    public static String TableRec_OnTime = "";
    public static String TableRec_MacNo = "";
    public static String TableRec_Cashier = "";
    public static String TableRec_ETD = "";
    public static String TableRec_TCode = "";
    public static String TableRec_TLogInTime = "";
    public static String TableRec_TCurTime = "";
    public static Date TableRec_TLoginDate;
    public static String TableRec_TOnAct = "";
    public static int TableRec_TItem = 0;
    public static int TableRec_TCustomer = 0;
    public static Double TableRec_TAmount = 0.00;
    public static Double TableRec_Food = 0.00;
    public static Double TableRec_Drink = 0.00;
    public static Double TableRec_Product = 0.00;
    public static Double TableRec_Service = 0.00;
    public static Double TableRec_ServiceAmt = 0.00;
    public static String TableRec_FastDisc = "";
    public static Double TableRec_FastDiscAmt = 0.00;
    public static String TableRec_EmpDisc = "";
    public static Double TableRec_EmpDiscAmt = 0.00;
    public static String TableRec_TrainDisc = "";
    public static Double TableRec_TrainDiscAmt = 0.00;
    public static String TableRec_MemDisc = "";
    public static Double TableRec_MemDiscAmt = 0.00;
    public static String TableRec_SubDisc = "";
    public static Double TableRec_SubDiscAmt = 0.00;
    public static Double TableRec_DiscBath = 0.00;
    public static Double TableRec_ProDiscAmt = 0.00;
    public static Double TableRec_SpaDiscAmt = 0.00;
    public static Double TableRec_CuponDiscAmt = 0.00;
    public static Double TableRec_ItemDiscAmt = 0.00;
    public static String TableRec_MemCode = "";
    public static String TableRec_MemName = "";
    public static Date TableRec_MemBegin;
    public static Date TableRec_MemEnd;
    public static Date TableRec_MemBrid;
    public static Double TableRec_MemCurAmt = 0.00;
    public static Double TableRec_Score = 0.00;
    public static Double TableRec_SumScoreal = 0.00;
    public static String TableRec_MemLastDate = "";
    public static Double TableRec_NetTotal = 0.00;
    public static Double TableRec_NetFood = 0.00;
    public static Double TableRec_NetDrink = 0.00;
    public static Double TableRec_NetProduct = 0.00;
    public static Double TableRec_NetVat = 0.00;
    public static Double TableRec_NetNonVat = 0.00;
    public static Double TableRec_Vat = 0.00;
    public static String TableRec_ArCode = "";
    public static int TableRec_AccrCr = 0;
    public static Double TableRec_ArPayment = 0.00;
    public static Double TableRec_PayAmt = 0.00;
    public static Double TableRec_Ton = 0.00;
    public static Double TableRec_Earnest = 0.00;
    public static Double TableRec_Gift_Voucher = 0.00;
    public static Double TableRec_Cash = 0.00;
    public static String TableRec_Cr_Bank = "";   //For SMP
    public static Double TableRec_Cr_CardAmt = 0.00;
    public static int TableRec_Cr_CurPoint = 0;
    public static int TableRec_Cr_SumPoint = 0;
    public static Double TableRec_Cr_PurseAmt = 0.00;
    public static Double TableRec_Cr_CouponAmt = 0.00;
    public static Double TableRec_Cr_TotCoupon = 0.00;
    public static String TableRec_Cr_Code1 = "";
    public static String TableRec_Cr_Name1 = "";
    public static Double TableRec_Cr_Charge = 0.00;
    public static Double TableRec_Cr_ChargeAmt = 0.00;
    public static Double TableRec_Cr_Redule = 0.00;
    public static String TableRec_Cr_CardNo1 = "";
    public static String TableRec_Cr_App_Code1 = "";
    public static Double TableRec_Cr_Amount1 = 0.00;
    public static Double TableRec_PrintTotal = 0.00;
    public static int TableRec_PrnCnt = 0;
    public static int TableRec_BillCopy = 0;
    public static String TableRec_PrnTime1 = "";
    public static String TableRec_PrnTime2 = "";
    public static String TableRec_BranCode = "";
    public static String TableRec_BranName = "";
    public static String TableRec_BranTel = "";
    public static String TableRec_BranTime = "";
    public static String TableRec_BranchDate = "";
    public static String TableRec_ChkBill = "";
    public static Time TableRec_ChkBillTime;  //Please Check Data Type
    public static String TableRec_MemBarcode = "N";
    public static String TableRec_PrintChkBill = "N";
    public static String TableRec_BarcodeLost = "N";
    public static String TableRec_BarcodeLostUser = "";
    public static String TableRec_BarcodeLostUserName = "";
    public static String TableRec_BarcodeLostTime = "";
    public static String TableRec_EmpCode = "";
    public static String TableRec_EmpName = "";
    public static String TableRec_CakeOrder_Id = "";
    public static Double TableRec_CakeOrder_Amount = 0.0;
    public static String TableRec_CakeOrder_Type = "";
    public static Double TableRec_CakeOrder_Deposite = 0.0;
    public static String TableRec_ChargeCode1 = "";
    public static String TableRec_ChargeName1 = "";
    public static int TableRec_ChargeType1 = 0;
    public static String TableRec_ChargeRemark1 = "";
    public static String TableRec_ChargeGroup1 = "";
    //TTableRec2 = Record   {Table Record .......}
    public static String TableRec2_RefNo = "";
    public static Date TableRec2_OnDate;
    public static String TableRec2_OnTime = "";
    public static String TableRec2_MacNo = "";
    public static String TableRec2_Cashier = "";
    public static String TableRec2_ETD = "";
    public static String TableRec2_TCode = "";
    public static String TableRec2_TLogInTime = "";
    public static String TableRec2_TCurTime = "";
    public static Date TableRec2_TLoginDate;
    public static String TableRec2_TOnAct = "";
    public static int TableRec2_TItem = 0;
    public static int TableRec2_TCustomer = 0;
    public static Double TableRec2_TAmount = 0.00;
    public static Double TableRec2_Food = 0.00;
    public static Double TableRec2_Drink = 0.00;
    public static Double TableRec2_Product = 0.00;
    public static Double TableRec2_Service = 0.00;
    public static Double TableRec2_ServiceAmt = 0.00;
    public static String TableRec2_FastDisc = "";
    public static Double TableRec2_FastDiscAmt = 0.00;
    public static String TableRec2_EmpDisc = "";
    public static Double TableRec2_EmpDiscAmt = 0.00;
    public static String TableRec2_TrainDisc = "";
    public static Double TableRec2_TrainDiscAmt = 0.00;
    public static String TableRec2_MemDisc = "";
    public static Double TableRec2_MemDiscAmt = 0.00;
    public static String TableRec2_SubDisc = "";
    public static Double TableRec2_SubDiscAmt = 0.00;
    public static Double TableRec2_DiscBath = 0.00;
    public static Double TableRec2_ProDiscAmt = 0.00;
    public static Double TableRec2_SpaDiscAmt = 0.00;
    public static Double TableRec2_CuponDiscAmt = 0.00;
    public static Double TableRec2_ItemDiscAmt = 0.00;
    public static String TableRec2_MemCode = "";
    public static String TableRec2_MemName = "";
    public static Date TableRec2_MemBegin;
    public static Date TableRec2_MemEnd;
    public static Date TableRec2_MemBrid;
    public static Double TableRec2_MemCurAmt = 0.00;
    public static Double TableRec2_Score = 0.00;
    public static Double TableRec2_SumScoreal = 0.00;
    public static String TableRec2_MemLastDate = "";
    public static Double TableRec2_NetTotal = 0.00;
    public static Double TableRec2_NetFood = 0.00;
    public static Double TableRec2_NetDrink = 0.00;
    public static Double TableRec2_NetProduct = 0.00;
    public static Double TableRec2_NetVat = 0.00;
    public static Double TableRec2_NetNonVat = 0.00;
    public static Double TableRec2_Vat = 0.00;
    public static String TableRec2_ArCode = "";
    public static int TableRec2_AccrCr = 0;
    public static Double TableRec2_ArPayment = 0.00;
    public static Double TableRec2_PayAmt = 0.00;
    public static Double TableRec2_Ton = 0.00;
    public static Double TableRec2_Earnest = 0.00;
    public static Double TableRec2_Gift_Voucher = 0.00;
    public static Double TableRec2_Cash = 0.00;
    public static String TableRec2_Cr_Bank = "";   //For SMP
    public static Double TableRec2_Cr_CardAmt = 0.00;
    public static int TableRec2_Cr_CurPoint = 0;
    public static int TableRec2_Cr_SumPoint = 0;
    public static Double TableRec2_Cr_PurseAmt = 0.00;
    public static Double TableRec2_Cr_CouponAmt = 0.00;
    public static Double TableRec2_Cr_TotCoupon = 0.00;
    public static String TableRec2_Cr_Code1 = "";
    public static String TableRec2_Cr_Name1 = "";
    public static Double TableRec2_Cr_Charge = 0.00;
    public static Double TableRec2_Cr_ChargeAmt = 0.00;
    public static Double TableRec2_Cr_Redule = 0.00;
    public static String TableRec2_Cr_CardNo1 = "";
    public static String TableRec2_Cr_App_Code1 = "";
    public static Double TableRec2_Cr_Amount1 = 0.00;
    public static Double TableRec2_PrintTotal = 0.00;
    public static int TableRec2_PrnCnt = 0;
    public static int TableRec2_BillCopy = 0;
    public static String TableRec2_PrnTime1 = "";
    public static String TableRec2_PrnTime2 = "";
    public static String TableRec2_BranCode = "";
    public static String TableRec2_BranName = "";
    public static String TableRec2_BranTel = "";
    public static String TableRec2_BranTime = "";
    public static String TableRec2_BranchDate = "";
    public static String TableRec2_ChkBill = "";
    public static Time TableRec2_ChkBillTime;  //Please Check Data Type
    public static String TableRec2_MemBarcode = "N";
    public static String TableRec2_PrintChkBill = "N";
    public static String TableRec2_BarcodeLost = "N";
    public static String TableRec2_BarcodeLostUser = "";
    public static String TableRec2_BarcodeLostUserName = "";
    public static String TableRec2_BarcodeLostTime = "";
    public static String TableRec2_EmpCode = "";
    public static String TableRec2_EmpName = "";
    //ProRec = Record 
    public static String Procode = "";
    public static String ProDesc = "";
    public static Date PDate1;
    public static Date PDate2;
    public static String PSTRDay = "";
    public static String PTime1S = "";
    public static String PTime1E = "";
    public static Double PDisc1 = 0.00;
    public static Double PSpDisc1 = 0.00;
    public static String PTS1 = "";
    public static String PTime2S = "";
    public static String PTime2E = "";
    public static Double PDisc2 = 0.00;
    public static Double PSpDisc2 = 0.00;
    public static String PTS2 = "";
    public static String PTime3S = "";
    public static String PTime3E = "";
    public static Double PDisc3 = 0.00;
    public static Double PSpDisc3 = 0.00;
    public static String PTS3 = "";
    public static String PType = "";
    public static int PSale1 = 0;
    public static int PFree1 = 0;
    public static int PSum1 = 0;
    public static Double PDiscFree1 = 0.00;
    public static int PSale2 = 0;
    public static int PFree2 = 0;
    public static int PSum2 = 0;
    public static Double PDiscFree2 = 0.00;
    public static int PSale3 = 0;
    public static int PFree3 = 0;
    public static int PSum3 = 0;
    public static Double PDiscFree3 = 0.00;
    public static int PSale41 = 0;
    public static int PSale42 = 0;
    public static int PSale43 = 0;
    public static int PFree41 = 0;
    public static int PFree42 = 0;
    public static int PFree43 = 0;
    public static String fixbranch = "";

}
