package program;

import printReport.PPrint;
import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import database.MySQLConnect;
import java.sql.Statement;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

public class RepMemAddTime extends javax.swing.JDialog {

    DefaultTableModel model2;
    SimpleDateFormat DatefmtThai = new SimpleDateFormat("dd/MM/yyyy", Locale.US);
    SimpleDateFormat Datefmt = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    SimpleDateFormat ShowDatefmt = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    DecimalFormat DecFmt = new DecimalFormat("###,##0.00");
    DecimalFormat IntFmt = new DecimalFormat("##,###,##0");
    Date date = new Date();
    Double XTotalCnt = 0.0;
    Double XTotalAmt = 0.0;
    PPrint prn = new PPrint();
    private POSHWSetup POSHW;

    /** Creates new form ArNotPay */
    public RepMemAddTime(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        model2 = (DefaultTableModel) tblShow.getModel();
        tblShow.setShowGrid(true);
        tblShow.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblShow.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblShow.setRowSelectionAllowed(true);
        tblShow.setGridColor(Color.gray);

        JTableHeader header = tblShow.getTableHeader();
        //header.setBackground(Color.yellow);
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 16));
                     //  1  2    3    4    5    6   7   8   9   10  11  12  13  14
        int[] ColSize = {30,80, 100, 200, 80, 80, 80,80,80,80,80,80,80,150,};
        for (int i = 0; i < 14; i++) {
            //int vColIndex = 0;
            TableColumn col = tblShow.getColumnModel().getColumn(i);
            col.setPreferredWidth(ColSize[i]);
        }
        ClearVariable();
        POSHW = POSHWSetup.Bean(Value.getMacno());
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ardate1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        ardate2 = new javax.swing.JFormattedTextField();
        cmdDateChoose3 = new javax.swing.JButton();
        cmdDateChoose4 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        bntOk = new javax.swing.JButton();
        bntPrint = new javax.swing.JButton();
        bntExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TotalCnt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TotalAmt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("รายงานการต่ออายุบัตรสมาชิก");
        setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setFocusable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel3.setText("ช่วงวันที่");

        ardate1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ardate1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        ardate1.setNextFocusableComponent(ardate2);
        ardate1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ardate1KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel4.setText("ถึง");

        ardate2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ardate2.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        ardate2.setNextFocusableComponent(tblShow);
        ardate2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ardate2KeyPressed(evt);
            }
        });

        cmdDateChoose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar.png"))); // NOI18N
        cmdDateChoose3.setFocusable(false);
        cmdDateChoose3.setRequestFocusEnabled(false);
        cmdDateChoose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDateChoose3ActionPerformed(evt);
            }
        });

        cmdDateChoose4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar.png"))); // NOI18N
        cmdDateChoose4.setFocusable(false);
        cmdDateChoose4.setRequestFocusEnabled(false);
        cmdDateChoose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDateChoose4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ardate1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDateChoose3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ardate2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDateChoose4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(ardate1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDateChoose3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ardate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDateChoose4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        bntOk.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        bntOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/ScrOnOff.jpg"))); // NOI18N
        bntOk.setText("F5 ประมวลผล");
        bntOk.setFocusable(false);
        bntOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntOk.setMargin(new java.awt.Insets(1, 1, 1, 1));
        bntOk.setRequestFocusEnabled(false);
        bntOk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOkActionPerformed(evt);
            }
        });
        jToolBar1.add(bntOk);

        bntPrint.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        bntPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/PaidIn2.jpg"))); // NOI18N
        bntPrint.setText("F10 พิมพ์");
        bntPrint.setFocusable(false);
        bntPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntPrint.setMargin(new java.awt.Insets(1, 1, 1, 1));
        bntPrint.setRequestFocusEnabled(false);
        bntPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(bntPrint);

        bntExit.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        bntExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/Logout.jpg"))); // NOI18N
        bntExit.setText("ออก(Exit)");
        bntExit.setFocusable(false);
        bntExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntExit.setMargin(new java.awt.Insets(1, 1, 1, 1));
        bntExit.setRequestFocusEnabled(false);
        bntExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExitActionPerformed(evt);
            }
        });
        jToolBar1.add(bntExit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblShow.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "V", "วันที่ (Date)", "รหัสสมาชิก", "ชื่อสมาชิก", "วันหมดอายุ", "ต่ออายุถึง", "ประเภท", "เงินสด", "แต้มสะสม", "ผู้บันทึก", "MacNo", "RefNo", "Void User", "Void Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShow.setFocusTraversalPolicyProvider(true);
        tblShow.setRowHeight(25);
        tblShow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblShowKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblShow);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel5.setText("จำนวนรายการทั้งสิ้น");

        TotalCnt.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        TotalCnt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalCnt.setText("jTextField1");
        TotalCnt.setFocusable(false);
        TotalCnt.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel6.setText("จำนวนเงินรวม");

        TotalAmt.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        TotalAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalAmt.setText("jTextField2");
        TotalAmt.setFocusable(false);
        TotalAmt.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalCnt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(TotalCnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Function");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuItem1.setText("ประมาลผล ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuItem2.setText("พิมพ์");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuItem3.setText("ออก (Exit)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1032, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void tblShowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblShowKeyPressed
   
    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        bntExitClick() ;
    }
    
    
}//GEN-LAST:event_tblShowKeyPressed

private void bntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExitActionPerformed
    bntExitClick();
}//GEN-LAST:event_bntExitActionPerformed

private void bntOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOkActionPerformed
    bntOKClick();
}//GEN-LAST:event_bntOkActionPerformed

private void bntPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPrintActionPerformed
    bntPrintClick();
}//GEN-LAST:event_bntPrintActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    bntOKClick();
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    bntPrintClick();
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    bntExitClick();
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
   //arcode1.requestFocus();
}//GEN-LAST:event_formWindowActivated

private void ardate1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ardate1KeyPressed
    if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        ardate2.requestFocus();
    }
}//GEN-LAST:event_ardate1KeyPressed

private void ardate2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ardate2KeyPressed
    if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        ardate1.requestFocus();
    }  
}//GEN-LAST:event_ardate2KeyPressed

private void cmdDateChoose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDateChoose3ActionPerformed
    Point point = cmdDateChoose3.getLocationOnScreen();
    point.setLocation(point.getX(), point.getY());
    util.DateChooseDialog dcd = new util.DateChooseDialog(new java.awt.Frame(), true, point);
    dcd.setVisible(true);
    //dcd.showDialog(new LookAndFeelFrame(), true, point);
    ardate1.setText(ShowDatefmt.format(dcd.getSelectDate().getTime()));
}//GEN-LAST:event_cmdDateChoose3ActionPerformed

private void cmdDateChoose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDateChoose4ActionPerformed
// TODO add your handling code here:
    Point point = cmdDateChoose4.getLocationOnScreen();
    point.setLocation(point.getX(), point.getY());
    util.DateChooseDialog dcd = new util.DateChooseDialog(new java.awt.Frame(), true, point);
    dcd.setVisible(true);
    //dcd.showDialog(new LookAndFeelFrame(), true, point);
    ardate2.setText(ShowDatefmt.format(dcd.getSelectDate().getTime()));
}//GEN-LAST:event_cmdDateChoose4ActionPerformed

  
    public void bntExitClick() {
        this.dispose();
    }

    public Boolean ChkValidDate() {
        Boolean RetVal = true;
        if (!PUtility.ChkDate(ardate1.getText())) {
            PUtility.ShowMsg("กรุณาป้อนวันที่ให้ถูกต้อง (Format=dd/MM/yyyy EXP 01/01/2009)");
            ardate1.requestFocus();
            RetVal = false;
        }
        if (!PUtility.ChkDate(ardate2.getText())) {
            PUtility.ShowMsg("กรุณาป้อนวันที่ให้ถูกต้อง (Format=dd/MM/yyyy EXP 01/01/2009)");
            ardate2.requestFocus();
            RetVal = false;
        }
        return RetVal;
    }

    public void bntPrintClick() {
        if (ChkValidDate()) {
            String TDate1 = ardate1.getText() ;
            String TDate2 = ardate2.getText() ;
            Date TempDate1 = new Date();
            Date TempDate2 = new Date();
            Double SumX = 0.0 ;
            Double SumY = 0.0 ;
            try {
                TempDate1 = ShowDatefmt.parse(TDate1);
                TempDate2 = ShowDatefmt.parse(TDate2);
            } catch (Exception e) {
            }
            if (!Value.getComPort().equals("NONE")) {
                if (prn.OpenPrint(Value.getComPort())) {
                    prn.InitPrinter();
                    prn.print("    รายงานการต่ออายุบัตรสมาชิก");
                    prn.print("ช่วงวันที่ " + ShowDatefmt.format(TempDate1) + " ถึง " + ShowDatefmt.format(TempDate2));
                    prn.print("");
                    prn.print(DatefmtThai.format(date) + " " + "Cashier:" + PublicVar._User + " Mac:" + Value.MACNO);
                    prn.print("----------------------------------------");
                    prn.print("วันที่         รหัสสมาชิก         เงินสด   แต้ม ");
                    prn.print("----------------------------------------");
                    try {
                        Statement stmt =  MySQLConnect.con.createStatement();
                        String SQLQuery = "select *from memaddtime left join memmaster on memaddtime.m_code=memmaster.m_code " +
                                "where (memaddtime.m_date>='" + Datefmt.format(TempDate1) + "') and (memaddtime.m_date<='" + Datefmt.format(TempDate2) + "') order by memaddtime.m_date";
                        ResultSet rec = stmt.executeQuery(SQLQuery);
                        rec.first();
                        if (rec.getRow() == 0) {
                        } else {
                            do {
                                SumX=SumX+rec.getDouble("m_amount") ;
                                SumY=SumY+rec.getDouble("m_Scoreamount") ;
                                prn.print(ShowDatefmt.format(rec.getDate("m_date")) + " " + PUtility.DataFullR(rec.getString("m_code"), 13) + " " + DecFmt.format(rec.getDouble("m_amount"))+"   "+DecFmt.format(rec.getDouble("m_Scoreamount")));
                                prn.print("  "+rec.getString("m_name")) ;
                                prn.print("  "+"หมดอายุ "+ShowDatefmt.format(rec.getDate("m_enddate")) + "  ต่ออายุถึง  "+ShowDatefmt.format(rec.getDate("m_newdate")) );
                                prn.print("  "+"User : "+rec.getString("m_user")+"   "+"MacNo/RefNo "+rec.getString("macno")+"/"+rec.getString("refno"));
                                if (rec.getString("m_void").equals("V")) {
                                    prn.print("  "+"##### ยกเลิก...โดย :"+rec.getString("m_uservoid")+" "+DatefmtThai.format(rec.getDate("m_voiddatetime")));
                                }
                            } while (rec.next());
                        }
                        rec.close();
                        stmt.close();
                    } catch (SQLException e) {
                        PUtility.showError(e.getMessage());
                    }
                    prn.print("----------------------------------------");
                    prn.print("ยอดค่าธรรมเนียมรวม    "+DecFmt.format(SumX)+"   "+DecFmt.format(SumY)) ;
                    prn.print("----------------------------------------");
                    prn.print("");
                    prn.print("");
                    prn.print("");
                    prn.print(POSHW.getHeading1());
                    prn.print(POSHW.getHeading2());
                    prn.print(POSHW.getHeading3());
                    prn.print(POSHW.getHeading4());
                    //Print_Str(" ");
                    prn.print("REG ID :" + Value.MACNO);
                    prn.CutPaper();
                    prn.closePrint();
                } else {
//                    PUtility.showError("เครื่องพิมพ์ใบกำกับภาษีไม่สามารถพิมพ์ได้ ...");
                }
            }
            TotalCnt.setText(IntFmt.format(XTotalCnt));
            TotalAmt.setText(DecFmt.format(XTotalAmt));
            tblShow.requestFocus();
        }
    }

    public void bntOKClick() {
        if (ChkValidDate()) {
            String TDate1 = ardate1.getText() ;
            String TDate2 = ardate2.getText() ;
            Date TempDate1 = new Date();
            Date TempDate2 = new Date();
            XTotalCnt = 0.0 ;
            XTotalAmt = 0.0 ;
            try {
                TempDate1 = ShowDatefmt.parse(TDate1);
                TempDate2 = ShowDatefmt.parse(TDate2);
            } catch (Exception e) {
               
            }
            int RowCount = model2.getRowCount();
            for (int i = 0; i <= RowCount - 1; i++) {
                 model2.removeRow(0);
            }
            try {
                Statement stmt =  MySQLConnect.con.createStatement();
                String SQLQuery = "select *from memaddtime left join memmaster on memaddtime.m_code=memmaster.m_code " +
                                "where (memaddtime.m_date>='" + Datefmt.format(TempDate1) + "') and (memaddtime.m_date<='" + Datefmt.format(TempDate2) + "') order by memaddtime.m_date";
                        ResultSet rec = stmt.executeQuery(SQLQuery);
                rec.first();
                if (rec.getRow() == 0) {
                } else {
                    do {
                        XTotalCnt++;
                        XTotalAmt = XTotalAmt + rec.getDouble("m_amount");
                        String VoidDate = "" ;
                        try {
                            VoidDate = DatefmtThai.format(rec.getDate("m_voiddatetime")) ;
                        } catch (Exception e) {
                            VoidDate = "" ;
                        }
                        Object[] input = 
                        {   rec.getString("m_void"),
                            ShowDatefmt.format(rec.getDate("m_date")),
                            rec.getString("m_code"),
                            rec.getString("m_name"),
                            ShowDatefmt.format(rec.getDate("m_enddate")),
                            ShowDatefmt.format(rec.getDate("m_newdate")),
                            rec.getString("addtype"),
                            rec.getDouble("m_amount"),
                            rec.getDouble("m_scoreamount"),
                            rec.getString("m_user"),
                            rec.getString("macno"),
                            rec.getString("refno"),
                            rec.getString("m_uservoid"),
                            VoidDate
                        };
                         model2.addRow(input);
                    } while (rec.next());
                    RowCount = model2.getRowCount();
                    showCell(0, 0);
                }
                rec.close();
                stmt.close();
            } catch (SQLException e) {
                PUtility.showError(e.getMessage());
            }
            TotalCnt.setText(IntFmt.format(XTotalCnt));
            TotalAmt.setText(DecFmt.format(XTotalAmt));
            tblShow.requestFocus();
        }
    }

    public void showCell(int row, int column) {
        if(row>0){
        Rectangle rect = tblShow.getCellRect(row, column, true);
        tblShow.scrollRectToVisible(rect);
        tblShow.clearSelection();
        tblShow.setRowSelectionInterval(row, row);
        }
    }

    public void ClearVariable() {
        ardate1.setText(ShowDatefmt.format(date));
        ardate2.setText(ShowDatefmt.format(date));
        XTotalCnt = 0.0;
        XTotalAmt = 0.0;
        TotalCnt.setText("");
        TotalAmt.setText("");
        ardate1.requestFocus();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ArNotPay dialog = new ArNotPay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotalAmt;
    private javax.swing.JTextField TotalCnt;
    private javax.swing.JFormattedTextField ardate1;
    private javax.swing.JFormattedTextField ardate2;
    private javax.swing.JButton bntExit;
    private javax.swing.JButton bntOk;
    private javax.swing.JButton bntPrint;
    private javax.swing.JButton cmdDateChoose3;
    private javax.swing.JButton cmdDateChoose4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblShow;
    // End of variables declaration//GEN-END:variables
}
